services:
  database:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: eniqlo_store_db_owner
      POSTGRES_PASSWORD: 4j2kxetmuPIK
      POSTGRES_DB: eniqlo_store_db
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: -p 5432
volumes:
  pg-data:
    driver: local
  cache:
    driver: local

